---
- name: Install Caddy
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if matrix_fqdn is set
      ansible.builtin.fail:
        msg: "Please define matrix_fqdn variable"
      when: matrix_fqdn is undefined

    - name: Populate OS facts
      ansible.builtin.setup:
        gather_subset:
          - min

    - name: Install and configure Caddy
      ansible.builtin.import_role:
        name: caddy
