---
- name: Check if Golang is installed
  ansible.builtin.stat:
    path: /usr/local/go
  register: golang_check

- name: Install Golang
  ansible.builtin.unarchive:
    src: "{{ golang_archive }}"
    remote_src: true
    dest: /usr/local/
  when: not golang_check.stat.exists

- name: Install xcaddy
  ansible.builtin.command: /usr/local/go/bin/go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

- name: Build Caddy with caddy-events-exec module
  ansible.builtin.command: /root/go/bin/xcaddy build --with github.com/mholt/caddy-events-exec --output /usr/local/bin/caddy
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

- name: Install Caddy service
  ansible.builtin.template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    mode: "0644"
    owner: root
    group: root
  notify: Reload systemd

- name: Copy Caddy configuration
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0640"
    owner: caddy
    group: caddy
  notify: Restart caddy

- name: Start Caddy service
  ansible.builtin.systemd:
    name: caddy.service
    state: started
    enabled: true

- name: Check if Coturn is installed
  ansible.builtin.stat:
    path: /etc/coturn
  register: coturn_check

- name: Copy coturn helper script
  ansible.builtin.template:
    src: copy-coturn-cert.sh.j2
    dest: /usr/local/bin/copy-coturn-cert.sh
    mode: "0750"
    owner: root
    group: root
  when: coturn_check.stat.exists

- name: Configure caddy permissions
  ansible.builtin.template:
    src: caddy.j2
    dest: /etc/sudoers.d/caddy
    mode: "0640"
    owner: root
    group: root
  when: coturn_check.stat.exists
