---
tuwunel_version: "1.6.1"
tuwunel_package_name: "v{{ tuwunel_version }}-release-all-x86_64-v2-linux-gnu-tuwunel.deb"
tuwunel_package_url: "https://github.com/matrix-construct/tuwunel/releases/download/v{{ tuwunel_version }}/{{ tuwunel_package_name }}"
tuwunel_local_install: false
