---
- name: Install required packages
  ansible.builtin.yum:
    name: coturn
    state: present

- name: Copy Coturn configuration
  ansible.builtin.template:
    src: turnserver.conf.j2
    dest: /etc/coturn/turnserver.conf
    mode: "0640"
    owner: "{{ coturn_user }}"
    group: "{{ coturn_user }}"
  notify: Restart coturn

- name: Start Coturn service
  ansible.builtin.systemd:
    name: coturn.service
    state: started
    enabled: true
